language: python
before_install: openssl version
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
python:
  - 2.6
  - 2.7
install:
  - pip install mock pytest pytest-django
  - python setup.py install
  - if [ $DJANGO = "1.4" ] ; then pip install https://github.com/django/django/archive/stable/1.4.x.zip#egg=django; fi
  - if [ $DJANGO = "1.5" ] ; then pip install https://github.com/django/django/archive/stable/1.5.x.zip#egg=django; fi
  - if [ $DJANGO = "1.6" ] ; then pip install https://github.com/django/django/archive/stable/1.6.x.zip#egg=django; fi
  - if [ $DJANGO = "1.7" ] ; then pip install https://github.com/django/django/archive/stable/1.7.x.zip#egg=django; fi
script:  ./runtests.sh
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.7
